### ISSUE TITLE
yaml.parser.ParserError on running convert.py

### ISSUE THREAD

**Issue by momo-the-monster** [daeken/Qtzweb#1]
On OS X 10.7.5
Python 2.7.1

I downloaded the zip from GitHub, installed the prerequisites, and tried running one of the example convert lines. When that didn't work, I tried a variety of files, no luck. Resulting output below:

---

Traceback (most recent call last):
  File "convert.py", line 338, in <module>
    classes = yaml.load(file('classes.yaml').read())
  File "build/bdist.macosx-10.7-intel/egg/yaml/**init**.py", line 71, in load
  File "build/bdist.macosx-10.7-intel/egg/yaml/constructor.py", line 37, in get_single_data
  File "build/bdist.macosx-10.7-intel/egg/yaml/composer.py", line 36, in get_single_node
  File "build/bdist.macosx-10.7-intel/egg/yaml/composer.py", line 55, in compose_document
  File "build/bdist.macosx-10.7-intel/egg/yaml/composer.py", line 84, in compose_node
  File "build/bdist.macosx-10.7-intel/egg/yaml/composer.py", line 133, in compose_mapping_node
  File "build/bdist.macosx-10.7-intel/egg/yaml/composer.py", line 84, in compose_node
  File "build/bdist.macosx-10.7-intel/egg/yaml/composer.py", line 127, in compose_mapping_node
  File "build/bdist.macosx-10.7-intel/egg/yaml/parser.py", line 98, in check_event
  File "build/bdist.macosx-10.7-intel/egg/yaml/parser.py", line 439, in parse_block_mapping_key
yaml.parser.ParserError: while parsing a block mapping
  in "<string>", line 1076, column 3:
      identifiers:
      ^
expected <block end>, but found '-'
  in "<string>", line 1079, column 3:
      -
      ^

**Comment by daeken** [comment]
Hey, thanks for the report.  I broke this as part of work I'm doing on the web editor :(  Fixed now!

**Comment by daeken** [comment]
Note to self: test the core functionality when making commits ;)
